### PR TITLE
fix fluid tank duplication in waila for machines with only one fluid slot

### LINKED ISSUE #23580: Waila always shows fluid input AND output slots even if machine only has one of them
### Your GTNH Discord Username

ableytner

### Your Pack Version

daily-378

### Your Server

private server

### Java Version

Java 25

### Type of Server

Vanilla Forge

### Your Expectation

Singleblock machines with only a fluid input OR a fluid output slot should only display the slot they have.

### The Reality

Waila always displays both slots.

Image

Image

Image

### Your Proposal

fix

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by danyadev**
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/23580

hasInputFluidSlot & hasOutputFluidSlot was set for every machine in https://github.com/GTNewHorizons/GT5-Unofficial/pull/5952, so we only need to wire everything up here

also now waila shows steam contents :letsfuckinggo:
image

### CODE REVIEW

File: src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachineBronze.java [hunk 1]
```diff
@@ -149,6 +151,12 @@ public boolean doesAutoOutput() {
         return false;
     }
 
+    @Override
+    public FluidTankInfo[] getTankInfo(ForgeDirection side) {
+        // bronze machines don't have fluid slots
```
Comment (koolkrafter5) [inline src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachineBronze.java]: Why not show the steam? We have the steam gauge in the UI so also showing it in WAILA seems fair.

**Review by koolkrafter5 — CHANGES_REQUESTED** [review]
Just one comment. The rest looks good.

File: src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachineBronze.java (hunk 1 above)
Comment (danyadev) [reply src/main/java/gregtech/api/metatileentity/implementations/MTEBasicMachineBronze.java]: added steam

**Review by Ruling-0 — APPROVED** [review]
Looks good after change addressing previous review.
