### PR TITLE
[MUI2] Upstream sync fixes

### LINKED ISSUE #24201: Daily 453 unable to interact with most gregtech single block machines
### Your GTNH Discord Username

LewisII

### Your Pack Version

Daily 453

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

When I right click interact with most gregtech single block machines, the game server crashes, both dedicated and local instance server exhibit the issue.
Issue persists on a fresh install as well

### Crash Report

[crash-2026-04-09_18.44.28-server.txt](https://github.com/user-attachments/files/26613187/crash-2026-04-09_18.44.28-server.txt)

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

### PR DESCRIPTION
**Pull request by TheYoingLad**
Fixed all issues related to the upstream sync that I could find.

Depends on GTNewHorizons/ModularUI2/pull/105

Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/24201

### CODE REVIEW

File: src/main/java/gregtech/common/gui/modularui/multiblock/godforge/panel/ExoticInputsListPanel.java [hunk 1]
```diff
@@ -72,6 +74,12 @@ private static void registerSyncValues(SyncHypervisor hypervisor) {
             .registerFor(Modules.EXOTIC, Panels.EXOTIC_INPUTS_LIST, hypervisor, hypervisor.getModule(Modules.EXOTIC));
 
         for (int i = 0; i < NUMBER_OF_INPUTS; i++) {
+            SyncHandler sh = hypervisor.getSyncManager(Modules.EXOTIC, Panels.EXOTIC_INPUTS_LIST)
+                .findSyncHandlerNullable("exotic_fluid_tanks:" + i);
+            if (sh != null) {
+                int a = 0;
```
Comment (chrombread) [inline src/main/java/gregtech/common/gui/modularui/multiblock/godforge/panel/ExoticInputsListPanel.java]: what is this for?

File: src/main/java/gregtech/common/gui/modularui/multiblock/dronecentre/panel/DroneConnectionListPanel.java [hunk 2]
```diff
@@ -184,14 +184,14 @@ private IWidget createFunctionArea(PanelSyncManager syncManager) {
             .child(
                 new UpdatableToggleButton(droneListHandler, groupHandler).size(16)
                     .value(syncManager.findSyncHandler("editMode", BooleanSyncValue.class))
-                    .background(GTGuiTextures.BUTTON_STANDARD)
+                    // .background(GTGuiTextures.BUTTON_STANDARD)
```
Comment (chrombread) [inline src/main/java/gregtech/common/gui/modularui/multiblock/dronecentre/panel/DroneConnectionListPanel.java]: why commented out?

**Review by chrombread — COMMENTED** [review]
some quick comments

File: src/main/java/gregtech/common/gui/modularui/multiblock/godforge/panel/ExoticInputsListPanel.java (hunk 1 above)
Comment (TheYoingLad) [reply src/main/java/gregtech/common/gui/modularui/multiblock/godforge/panel/ExoticInputsListPanel.java]: good catch, i used that for debugging but forgot to delete it

File: src/main/java/gregtech/common/gui/modularui/multiblock/dronecentre/panel/DroneConnectionListPanel.java (hunk 2 above)
Comment (TheYoingLad) [reply src/main/java/gregtech/common/gui/modularui/multiblock/dronecentre/panel/DroneConnectionListPanel.java]: thanks, i forgot to delete that

**Comment by PLASMAchicken** [comment]
I edited your PR description to automatically close Issue https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/24201 once merged.

**Review by chrombread — APPROVED** [review]
thanks!
