### PR TITLE
Fix dissolution tank input parsing

### LINKED ISSUE #22482: Dissolution tank doesn't see 2 water hatches
### Your GTNH Discord Username

Ironman333

### Your Pack Version

2.8.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Dissolution tank can work with multiple input hatches, therefore I expect it recognizes multiple water hatches and includes them for ratio multiplication.

### The Reality

It looks like it's only taking into account 1 input hatch ignoring the other one when calculating ratio. I took a quick look at the code MTEDissolutionTank.java - checkRatio, but not sure how mFluidInputs are calculated. Here's how I reproed it ([thread on reddit](https://www.reddit.com/r/GTNH/comments/1oefclr/dissolution_tank_automation/)):
I have 1 LV input hatch full of monazite mud - 16kl. I have 1 MV (32kl) and 1 EV (128kl) input hatches with water - so all inputs are 16kl monazite : 160kl water. However, the tank complains that the ratio is wrong. It reproed reliably for me. I assume it doesn't add water from both hatches into calculation but when failing recipe it actually pulls inputs from all available hatches (with circuit 9 it took all MV and part of EV water when voiding input after failed check).

### Your Proposal

Dissolution tank should take all available inputs into account when calculating ratio.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by LooseEthics**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/22482

Changed checkRatio to iterate over all input FluidStacks instead of just 2. This allows single fluid to be spread across multiple hatches. 
For example to have a 128k and 32k hatches for one input and 16k for the other to achieve a 10:1 ratio.
Also allows the player set up a single tank for multiple recipes if for some god forsaken reason they choose to.

Furthermore flipped the return expression, division allows for imprecise ratios due to int truncation.

### CODE REVIEW

File: src/main/java/gtnhlanth/common/tileentity/MTEDissolutionTank.java [hunk 1]
```diff
@@ -139,40 +139,32 @@ public boolean supportsSingleRecipeLocking() {
     }
 
     private boolean checkRatio(GTRecipe tRecipe, List<FluidStack> tFluidInputs) {
+        /*
+         * System.out.println("Called checkRatio with:");
+         * for (FluidStack f : tFluidInputs) {
+         * System.out.println(f.getUnlocalizedName() + " " + f.amount);
+         * }
+         */
```
Comment (boubou19) [inline src/main/java/gtnhlanth/common/tileentity/MTEDissolutionTank.java]: dead code

File: src/main/java/gtnhlanth/common/tileentity/MTEDissolutionTank.java [hunk 2]
```diff
@@ -139,40 +139,32 @@ public boolean supportsSingleRecipeLocking() {
...
-                } else return false;
-
-            } else return false;
-
-        return majorAmount / tRecipe.mSpecialValue == minorAmount;
+                    minorAmount += f.amount;
+                }
+        }
+
+        // System.out.println("Major: " + majorAmount + ", minor: " + minorAmount);
```
Comment (boubou19) [inline src/main/java/gtnhlanth/common/tileentity/MTEDissolutionTank.java]: dead code

Comment (LooseEthics) [reply src/main/java/gtnhlanth/common/tileentity/MTEDissolutionTank.java]: gone

**Review by Ruling-0 — APPROVED** [review]

**Comment by vnesterovskyi** [comment]
I just saw it, thank you @LooseEthics!
